#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-syntax
Version  : 1.2.0
Release  : 3
URL      : https://rubygems.org/downloads/syntax-1.2.0.gem
Source0  : https://rubygems.org/downloads/syntax-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
= Syntax
A syntax highlighting a library for Ruby.
This fork is maintained and version 1.1.0 has been published from it. However, there's currently none or not much new development going on here and the original author, @jamis[https://github.com/jamis], recommends using CodeRay[http://coderay.rubychan.de], over this library.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n syntax-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-syntax.gemspec

%build
gem build rubygem-syntax.gemspec

%install
gem_dir=$(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .${gem_dir} \
--bindir .%{_bindir} \
syntax-1.2.0.gem

mkdir -p %{buildroot}${gem_dir}
cp -pa .${gem_dir}/* \
%{buildroot}${gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/syntax-1.2.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/AnsiC/add_type-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/AnsiC/cdesc-AnsiC.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/AnsiC/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/CSS21/cdesc-CSS21.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/CSS21/m-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/CSS21/macro-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/CSS21/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/CSS21/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/CSS21/token-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Convertors/Abstract/cdesc-Abstract.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Convertors/Abstract/for_syntax-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Convertors/Abstract/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Convertors/Abstract/tokenizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Convertors/HTML/cdesc-HTML.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Convertors/HTML/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Convertors/HTML/html_escape-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Convertors/cdesc-Convertors.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Default/cdesc-Default.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Default/tokenize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Fortran/cdesc-Fortran.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Fortran/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Javascript/cdesc-Javascript.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Javascript/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Ruby/cdesc-Ruby.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Ruby/scan_delimited_region-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Ruby/scan_heredoc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Ruby/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Ruby/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/SQLite/add_function-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/SQLite/cdesc-SQLite.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/SQLite/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Token/cdesc-Token.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Token/group-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Token/instruction-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Token/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/append-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/cdesc-Tokenizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/chunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/delegate-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/end_region-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/finish-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/flush_chunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/group-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/set-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/start_group-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/start_region-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/subgroup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/subtokenize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/teardown-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Tokenizer/tokenize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/Version/cdesc-Version.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/XML/cdesc-XML.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/XML/scan_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/XML/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/XML/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/YAML/cdesc-YAML.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/YAML/scan_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/YAML/step-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/all-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/cdesc-Syntax.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/Syntax/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/syntax-1.2.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/CHANGELOG
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/common.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/convertors/abstract.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/convertors/html.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/lang/ansic.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/lang/css21.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/lang/fortran.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/lang/javascript.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/lang/ruby.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/lang/sqlite.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/lang/xml.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/lang/yaml.rb
/usr/lib64/ruby/gems/2.2.0/gems/syntax-1.2.0/lib/syntax/version.rb
/usr/lib64/ruby/gems/2.2.0/specifications/syntax-1.2.0.gemspec
