#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-syntax
Version  : 1.2.0
Release  : 6
URL      : https://rubygems.org/downloads/syntax-1.2.0.gem
Source0  : https://rubygems.org/downloads/syntax-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
= Syntax
A syntax highlighting a library for Ruby.
This fork is maintained and version 1.1.0 has been published from it. However, there's currently none or not much new development going on here and the original author, @jamis[https://github.com/jamis], recommends using CodeRay[http://coderay.rubychan.de], over this library.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n syntax-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-syntax.gemspec

%build
gem build rubygem-syntax.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
syntax-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/syntax-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/CHANGELOG
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/common.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/convertors/abstract.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/convertors/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/lang/ansic.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/lang/css21.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/lang/fortran.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/lang/javascript.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/lang/ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/lang/sqlite.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/lang/xml.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/lang/yaml.rb
/usr/lib64/ruby/gems/2.3.0/gems/syntax-1.2.0/lib/syntax/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/syntax-1.2.0.gemspec
